language: go

script:
  - go test -short ./...
  - go test ./... -run RandomizeFast -count=512
  - go test ./... -run RandomizeSlow -count=32

go_import_path: github.com/emiregis-meli/go-crypto

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master
